#!/usr/bin/env node
'use strict';
const fs = require('fs');

const args = process.argv.slice(2);

let socketPath = null;
for (const arg of args) {
  if (arg.startsWith('--socket=')) {
    socketPath = arg.slice('--socket='.length);
  }
}

if (!socketPath) {
  process.stderr.write('fake-tailscaled: --socket required\n');
  process.exit(1);
}

// Create socket file immediately so isSocketResponding() sees it
fs.writeFileSync(socketPath, '');

// Keep alive until SIGTERM/SIGINT
const interval = setInterval(() => {}, 1000);

function shutdown() {
  clearInterval(interval);
  try { fs.unlinkSync(socketPath); } catch {}
  process.exit(0);
}

process.on('SIGTERM', shutdown);
process.on('SIGINT', shutdown);
